services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-mpl-25-r1-mpl-25-r1-db.j.aivencloud.com:19305/defaultdb?sslmode=REQUIRED
      SPRING_DATASOURCE_USERNAME: avnadmin
      SPRING_DATASOURCE_PASSWORD: AVNS_qsv8YuugKZSJH1IPRpi
